### ISSUE TITLE
Does this work with Sublime Text 3?

### ISSUE THREAD

**Issue by dylan-k** [chagel/itodo#6]
It looks like it has been a while since this was updated. Does it work with Sublime Text 3?

**Comment by arpit1997** [comment]
No It does not work with sublime Text 3 at least not yet. A few suggestion for @chagel 
- Put all source codes in src folder .
- update your package in [Package Control](http://packagecontrol.io) it is not latest version there.
- One more thing is to clear state the installation instructions like where to clone the repo specifically for windows, ubuntu or mac. 
- Last but not least follow a code style (PEP8) and use docstrings in the code
